version: '3.8'

volumes:
  postgres_data:

networks:
  meteo-network:

services:

  # ===============================
  # Database (PostgreSQL)
  # ===============================
  meteo-postgres:
    container_name: meteo-postgres
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
          test: [ "CMD-SHELL", "pg_isready -U postgres" ]
          interval: 5s
          retries: 5
    networks:
      - meteo-network

  # ===============================
  # Console App (Dotnet)
  # ===============================
  meteo-app:
    container_name: meteo-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      meteo-postgres:
        condition: service_healthy
    environment:
      DOTNET_ENVIRONMENT: ${DOTNET_ENVIRONMENT}
      ConnectionStrings__DBConnection: "User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Host=meteo-postgres;Port=5432;Database=${POSTGRES_DB};Include Error Detail=true;"
    networks:
      - meteo-network